// flow-typed signature: 15b1f122ebd4eb064bcc49b96d37f8ab
// flow-typed version: <<STUB>>/disconnect_v^1.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'disconnect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'disconnect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'disconnect/lib/client' {
  declare module.exports: any;
}

declare module 'disconnect/lib/collection' {
  declare module.exports: any;
}

declare module 'disconnect/lib/database' {
  declare module.exports: any;
}

declare module 'disconnect/lib/error' {
  declare module.exports: any;
}

declare module 'disconnect/lib/list' {
  declare module.exports: any;
}

declare module 'disconnect/lib/marketplace' {
  declare module.exports: any;
}

declare module 'disconnect/lib/oauth' {
  declare module.exports: any;
}

declare module 'disconnect/lib/queue' {
  declare module.exports: any;
}

declare module 'disconnect/lib/user' {
  declare module.exports: any;
}

declare module 'disconnect/lib/util' {
  declare module.exports: any;
}

declare module 'disconnect/lib/wantlist' {
  declare module.exports: any;
}

declare module 'disconnect/test/all' {
  declare module.exports: any;
}

declare module 'disconnect/test/client' {
  declare module.exports: any;
}

declare module 'disconnect/test/error' {
  declare module.exports: any;
}

declare module 'disconnect/test/queue' {
  declare module.exports: any;
}

declare module 'disconnect/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'disconnect/index' {
  declare module.exports: $Exports<'disconnect'>;
}
declare module 'disconnect/index.js' {
  declare module.exports: $Exports<'disconnect'>;
}
declare module 'disconnect/lib/client.js' {
  declare module.exports: $Exports<'disconnect/lib/client'>;
}
declare module 'disconnect/lib/collection.js' {
  declare module.exports: $Exports<'disconnect/lib/collection'>;
}
declare module 'disconnect/lib/database.js' {
  declare module.exports: $Exports<'disconnect/lib/database'>;
}
declare module 'disconnect/lib/error.js' {
  declare module.exports: $Exports<'disconnect/lib/error'>;
}
declare module 'disconnect/lib/list.js' {
  declare module.exports: $Exports<'disconnect/lib/list'>;
}
declare module 'disconnect/lib/marketplace.js' {
  declare module.exports: $Exports<'disconnect/lib/marketplace'>;
}
declare module 'disconnect/lib/oauth.js' {
  declare module.exports: $Exports<'disconnect/lib/oauth'>;
}
declare module 'disconnect/lib/queue.js' {
  declare module.exports: $Exports<'disconnect/lib/queue'>;
}
declare module 'disconnect/lib/user.js' {
  declare module.exports: $Exports<'disconnect/lib/user'>;
}
declare module 'disconnect/lib/util.js' {
  declare module.exports: $Exports<'disconnect/lib/util'>;
}
declare module 'disconnect/lib/wantlist.js' {
  declare module.exports: $Exports<'disconnect/lib/wantlist'>;
}
declare module 'disconnect/test/all.js' {
  declare module.exports: $Exports<'disconnect/test/all'>;
}
declare module 'disconnect/test/client.js' {
  declare module.exports: $Exports<'disconnect/test/client'>;
}
declare module 'disconnect/test/error.js' {
  declare module.exports: $Exports<'disconnect/test/error'>;
}
declare module 'disconnect/test/queue.js' {
  declare module.exports: $Exports<'disconnect/test/queue'>;
}
declare module 'disconnect/test/util.js' {
  declare module.exports: $Exports<'disconnect/test/util'>;
}
